<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInite266dd732681309501228670ec140987
{
    public static $prefixesPsr0 = array (
        'C' => 
        array (
            'CoinRemitter' => 
            array (
                0 => __DIR__ . '/..' . '/coinremitterphp/coinremitter-php/src',
            ),
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixesPsr0 = ComposerStaticInite266dd732681309501228670ec140987::$prefixesPsr0;
            $loader->classMap = ComposerStaticInite266dd732681309501228670ec140987::$classMap;

        }, null, ClassLoader::class);
    }
}
